FROM debian:oldstable

# Install necessary packages
ARG PACKAGES="nginx openssl"
RUN apt update && apt upgrade -y && apt install -y $PACKAGES

# Copy SSL certificates
COPY certificates/localhost.crt /etc/ssl/certs/
COPY certificates/localhost.key /etc/ssl/private/

# Copy Nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Expose HTTPS port
EXPOSE 443

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]
