FROM debian:oldstable

ARG PCKGS="nginx"

RUN apt update && apt upgrade -y && apt install -y $PCKGS

COPY nginx.conf /etc/nginx

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 81

CMD ["nginx", "-g", "daemon off;"]