FROM debian:oldstable

ARG PCKGS=" php-fpm \
			php-mysql \
			curl \
			mariadb-client \
			netcat"

RUN apt update && apt upgrade -y && apt install -y $PCKGS

RUN mkdir /run/php/ && chmod 755 /run/php

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod a+x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp \
    && ln -s /usr/local/bin/wp /usr/bin/wp

RUN sed -i 's:listen = /run/php/php7.4-fpm.sock:listen = 9000:g' /etc/php/7.4/fpm/pool.d/www.conf

COPY setup_wordpress.sh /home/
RUN chmod +x /home/setup_wordpress.sh

ENTRYPOINT ["/home/setup_wordpress.sh"]

CMD ["php-fpm7.4", "-F", "-R"]
